# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='bidirectional',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\rbidirectional\"\xca\x02\n\x04\x44\x61ta\x12\x13\n\x06\x61\x63tion\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x63lient_username\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0f\x63lient_password\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1f\n\x12recipient_username\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x14\n\x07message\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1f\n\x12\x61vailable_messages\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x1a\n\rlist_accounts\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\t\n\x07_actionB\x12\n\x10_client_usernameB\x12\n\x10_client_passwordB\x15\n\x13_recipient_usernameB\n\n\x08_messageB\x15\n\x13_available_messagesB\x10\n\x0e_list_accounts2T\n\rBidirectional\x12\x43\n\x11GetServerResponse\x12\x13.bidirectional.Data\x1a\x13.bidirectional.Data\"\x00(\x01\x30\x01\x62\x06proto3'
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='bidirectional.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='bidirectional.Data.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_username', full_name='bidirectional.Data.client_username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_password', full_name='bidirectional.Data.client_password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipient_username', full_name='bidirectional.Data.recipient_username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='bidirectional.Data.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available_messages', full_name='bidirectional.Data.available_messages', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list_accounts', full_name='bidirectional.Data.list_accounts', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_action', full_name='bidirectional.Data._action',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_client_username', full_name='bidirectional.Data._client_username',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_client_password', full_name='bidirectional.Data._client_password',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_recipient_username', full_name='bidirectional.Data._recipient_username',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_message', full_name='bidirectional.Data._message',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_available_messages', full_name='bidirectional.Data._available_messages',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_list_accounts', full_name='bidirectional.Data._list_accounts',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=360,
)

_DATA.oneofs_by_name['_action'].fields.append(
  _DATA.fields_by_name['action'])
_DATA.fields_by_name['action'].containing_oneof = _DATA.oneofs_by_name['_action']
_DATA.oneofs_by_name['_client_username'].fields.append(
  _DATA.fields_by_name['client_username'])
_DATA.fields_by_name['client_username'].containing_oneof = _DATA.oneofs_by_name['_client_username']
_DATA.oneofs_by_name['_client_password'].fields.append(
  _DATA.fields_by_name['client_password'])
_DATA.fields_by_name['client_password'].containing_oneof = _DATA.oneofs_by_name['_client_password']
_DATA.oneofs_by_name['_recipient_username'].fields.append(
  _DATA.fields_by_name['recipient_username'])
_DATA.fields_by_name['recipient_username'].containing_oneof = _DATA.oneofs_by_name['_recipient_username']
_DATA.oneofs_by_name['_message'].fields.append(
  _DATA.fields_by_name['message'])
_DATA.fields_by_name['message'].containing_oneof = _DATA.oneofs_by_name['_message']
_DATA.oneofs_by_name['_available_messages'].fields.append(
  _DATA.fields_by_name['available_messages'])
_DATA.fields_by_name['available_messages'].containing_oneof = _DATA.oneofs_by_name['_available_messages']
_DATA.oneofs_by_name['_list_accounts'].fields.append(
  _DATA.fields_by_name['list_accounts'])
_DATA.fields_by_name['list_accounts'].containing_oneof = _DATA.oneofs_by_name['_list_accounts']
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:bidirectional.Data)
  })
_sym_db.RegisterMessage(Data)



_BIDIRECTIONAL = _descriptor.ServiceDescriptor(
  name='Bidirectional',
  full_name='bidirectional.Bidirectional',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=362,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetServerResponse',
    full_name='bidirectional.Bidirectional.GetServerResponse',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIDIRECTIONAL)

DESCRIPTOR.services_by_name['Bidirectional'] = _BIDIRECTIONAL

# @@protoc_insertion_point(module_scope)
